table 'Customer Status Member'
	lineageTag: dc4f2a1f-df58-489d-948d-847ac6d16e11

	column CustomerID
		dataType: string
		lineageTag: 58ee3aea-1c1a-4ee8-8749-8debd709655d
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column AgeGroup
		dataType: string
		lineageTag: 8f71a92d-a930-4853-b348-de2fc55ddd93
		summarizeBy: none
		sourceColumn: AgeGroup

		annotation SummarizationSetBy = Automatic

	column MemberStatus
		dataType: string
		lineageTag: 4d24de45-f59c-4a10-9588-4554bef127d9
		summarizeBy: none
		sourceColumn: MemberStatus

		annotation SummarizationSetBy = Automatic

	column TierStatus
		dataType: string
		lineageTag: a252ed06-42a0-43aa-bdb1-f9b42d9d70be
		summarizeBy: none
		sourceColumn: TierStatus

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Customer Status Member' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jhermawa\OneDrive - Capgemini\Documents\Demo Dashboard\dataset_retail_dashboard.xlsx"), null, true),
				    Customer_Sheet = Source{[Item="Customer",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Customer_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerID", type text}, {"AgeGroup", type text}, {"MemberStatus", type text}, {"TierStatus", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","Gold","Platinum",Replacer.ReplaceText,{"TierStatus"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Silver","Gold",Replacer.ReplaceText,{"TierStatus"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

