table Product
	lineageTag: 12eae9d7-13fd-4495-92c4-5440b70477c3

	column ProductID
		dataType: string
		lineageTag: c0b49f48-8944-4145-bf54-4377cfe192ad
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: ede45dbb-6206-4280-9259-fe6d1eba3f18
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: f1a4a913-cb74-4ffb-a224-597ae13f1690
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: a52d1c3e-ce02-48e6-9a33-2a4e1a21c0c1
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Seasonal Type'
		dataType: string
		lineageTag: 7938244e-f351-4074-abbb-0c9021b7dc2a
		summarizeBy: none
		sourceColumn: Seasonal Type

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jhermawa\OneDrive - Capgemini\Documents\Demo Dashboard\dataset_retail_dashboard.xlsx"), null, true),
				    Product_Sheet = Source{[Item="Product",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Product_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductID", type text}, {"Product Name", type text}, {"Brand", type text}, {"Category", type text}, {"Seasonal Type", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","Home & Living","Home",Replacer.ReplaceText,{"Category"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

