table Sales
	lineageTag: 37759343-4ad4-49c9-aa75-1a0efd2fe0e1

	measure 'Total Sales' = SUM(Sales[Sales Amount])
		lineageTag: 4d1f383d-75f6-425f-990e-accf632cb1bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = SUM(Sales[Profit Amount])
		lineageTag: b651fc11-81d8-48c5-bce5-01bd43108b50

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Transactions' = SUM(Sales[Transaction Count])
		formatString: 0
		lineageTag: 977f9320-9e3c-47fc-bd42-b267dd941330

	measure 'Average Order Value' = DIVIDE([Total Sales], [Total Transactions], 0)
		formatString: "$#,##0.00"
		lineageTag: a7f2e8c9-b1d4-4e8f-9a3c-5f7d6b8e2c1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Cost' = [Total Sales] - [Total Profit]
		lineageTag: 88946b7f-5ef3-4bd1-96b1-5fe8a0356b57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Cost/ Product' = DIVIDE([Total Cost], COUNTROWS(Sales))
		lineageTag: 1434a08d-43f7-45f2-8291-4ddff44af4ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Member Sales' = CALCULATE([Total Sales], Customer[MemberStatus] = "Member")
		lineageTag: a6ceb3b0-df65-4c6b-904f-2e10d7d7371e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Member Sales %' = DIVIDE([Member Sales], [Total Sales])
		lineageTag: 787f3943-10a8-4d96-8547-41f3c6c036d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Category Month Share %' =
			
			DIVIDE(
			    [Total Sales],
			    CALCULATE(
			        [Total Sales],
			        ALL(Sales[Month Name], Sales[Month No])
			    ),
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 051e039e-9cd9-432a-b539-1fc855c4efac

	measure 'Total Units Sold' = SUM(Sales[Units Sold])
		formatString: 0
		lineageTag: 14e500c4-b406-4632-8720-4123f091c77c

	measure 'Sales Contribution %' =
			
			DIVIDE(
			    [Total Sales],
			    CALCULATE(
			        [Total Sales],
			        ALL(Store[City])
			    ),
			    0
			)
		lineageTag: 203fb315-e4d2-4826-aa58-472d975765a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Transaction Contribution %' =
			
			DIVIDE(
			    [Total Transactions],
			    CALCULATE(
			        [Total Transactions],
			        ALL(Store[City])
			    ),
			    0
			)
		lineageTag: 19de1f88-368f-4c7b-9f2e-94f1cf4cbb77

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Count' = DISTINCTCOUNT(Sales[CustomerID])
		formatString: 0
		lineageTag: ec94b8d5-de88-488b-b59f-3088efdcdb03

	measure 'Total Customer Sales' = DISTINCTCOUNT ( Sales[CustomerID] )
		formatString: 0
		lineageTag: f7e1319a-c6b6-4a35-a590-6e8f39547183

	measure 'Top City by Customer' = ```
			
			VAR SummaryTable =
			    SUMMARIZE (
			        Store,
			        Store[City],
			        "CustomerCount", [Total Customer Sales]
			    )
			VAR TopRow =
			    TOPN (
			        1,
			        SummaryTable,
			        [CustomerCount], DESC,
			        Store[City], ASC
			    )
			RETURN
			MAXX ( TopRow, Store[City] )
			
			```
		lineageTag: 9b3baad8-6b42-4c30-8160-184436b25863

	measure 'Top 5 Countries by Sales' =
			VAR CitySales =
			    ADDCOLUMNS(
			        SUMMARIZE(
			            Store,
			            Store[City]
			        ),
			        "SalesAmount", CALCULATE([Total Sales])
			    )
			VAR TopCities =
			    TOPN(
			        5,
			        CitySales,
			        [SalesAmount], DESC,
			        Store[City], ASC
			    )
			RETURN
			CONCATENATEX(
			    TopCities,
			    Store[City],
			    ", ",
			    [SalesAmount],
			    DESC
			)
		lineageTag: 0d1b2e3f-4a5b-6c7d-8e9f-0123456789ab

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 16f79028-94c1-4746-86ff-a2f0213f53f7
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: dfc7c396-bd84-453b-af8f-ff1da103a38c
			defaultHierarchy: LocalDateTable_41614d07-ff71-46d2-98cb-4db2f81dd2be.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 3f3221ba-af07-400a-b208-ab94a7639f0c
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month No'
		dataType: int64
		formatString: 0
		lineageTag: 9fb7658d-5ba9-482c-af6f-17dc0782a920
		summarizeBy: sum
		sourceColumn: Month No

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: e1fd2ea3-effa-434f-94a4-3cce2726300d
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Month No'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column StoreID
		dataType: string
		lineageTag: 61d0dec4-476b-40cc-9c40-2e8d136003ff
		summarizeBy: none
		sourceColumn: StoreID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		lineageTag: bb3ba536-5178-4cc0-9be9-726432aeb233
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		lineageTag: d33d1e18-19eb-4b6c-a4af-d81b19a75c0a
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column 'Payment Method'
		dataType: string
		lineageTag: afb98934-ea11-470a-ac8d-194d22394f81
		summarizeBy: none
		sourceColumn: Payment Method

		annotation SummarizationSetBy = Automatic

	column 'Sales Amount'
		dataType: double
		lineageTag: 9fcad063-f19d-448f-bce7-0036975423f3
		summarizeBy: sum
		sourceColumn: Sales Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Amount'
		dataType: double
		lineageTag: 4d8483ff-68d0-4de1-b31c-f1ec8f4c0c4b
		summarizeBy: sum
		sourceColumn: Profit Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: af89f893-dd40-414e-9b52-d4a49599a38d
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Transaction Count'
		dataType: int64
		formatString: 0
		lineageTag: c60fe192-ae9a-406f-a42e-5e4f584cc36a
		summarizeBy: sum
		sourceColumn: Transaction Count

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jhermawa\OneDrive - Capgemini\Documents\Demo Dashboard\dataset_retail_dashboard.xlsx"), null, true),
				    Sales_Sheet = Source{[Item="Sales",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sales_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Year", Int64.Type}, {"Month No", Int64.Type}, {"Month Name", type text}, {"StoreID", type text}, {"ProductID", type text}, {"CustomerID", type text}, {"Payment Method", type text}, {"Sales Amount", type number}, {"Profit Amount", type number}, {"Units Sold", Int64.Type}, {"Transaction Count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

