table Store
	lineageTag: 0500d3f7-d1b3-499b-901a-f2deb337b235

	measure 'Selected City' = SELECTEDVALUE(Store[City], "All Cities")
		lineageTag: 7be2051e-74cd-4d64-9ef2-ad598fe884a9

	column StoreID
		dataType: string
		lineageTag: 66c2097a-214d-4c6a-b9b4-189bfef3a572
		summarizeBy: none
		sourceColumn: StoreID

		annotation SummarizationSetBy = Automatic

	column StoreName
		dataType: string
		lineageTag: c4f92016-afc8-443c-a349-ce4db643796f
		summarizeBy: none
		sourceColumn: StoreName

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 7b348b1d-3bbe-4adb-b757-998696374dd0
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'City Tier'
		dataType: string
		lineageTag: d0791d65-915e-42ca-8522-4d691a7a0f3b
		summarizeBy: none
		sourceColumn: City Tier

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 7be0a7d7-7837-45b4-9259-ac5fc22909b1
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 1418d1b3-eb1d-4857-b9e0-6e077e32e710
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Store = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jhermawa\OneDrive - Capgemini\Documents\Demo Dashboard\dataset_retail_dashboard.xlsx"), null, true),
				    Store_Sheet = Source{[Item="Store",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Store_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"StoreID", type text}, {"StoreName", type text}, {"City", type text}, {"City Tier", type text}, {"Country", type text}, {"Region", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

